name: CI - Train & Build Model

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install mlflow==2.19.0 scikit-learn pandas numpy

      - name: Run MLflow Project
        working-directory: MLProject
        run: |
          python modelling.py --n_estimators 100 --max_depth 5 --random_state 42

      - name: Upload MLflow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: MLProject/mlruns/
          retention-days: 30

  build-docker:
    runs-on: ubuntu-latest
    needs: train-model

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./MLProject
          file: ./MLProject/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/iris-classification:latest
